Internal. Rework `testify` script to run `cobra -testify` per major test directory instead of just once. Motivated by stability issues that appeared on Mono 2.10 after switching to reflection-only loading.

diff --git a/Source/bin/testify b/Source/bin/testify
--- a/Source/bin/testify
+++ b/Source/bin/testify
@@ -1,29 +1,77 @@
 #!/bin/bash
 cd "`dirname "$0"`" ; cd ..
 
-clean() {
+tmpOutputFile=r-testify-all.text
+testifyOutputFile=r-testify.text
+
+failures=0
+successes=0
+
+if [ $# -eq 0 ] ; then
+	dirs=`ls -d -1 ../Tests/*-* | sort`
+else
+	dirs="$@"
+fi
+
+setUp() {
+	# clean Tests
+	pushd . > /dev/null
 	cd ../Tests/
 	./clean
-	cd ../Source
-}
+	popd > /dev/null
 	
-# clear
+	# set aside last output
+	if [ -f $testifyOutputFile ]; then
+		mv $testifyOutputFile r-testify-last.text
+	fi
 
-clean
+	# remove tmp output collection file
+	echo "Started: `date`" > $tmpOutputFile
 
-# set mono path to support using the Cobra.Core.dll in this directory
-export MONO_PATH="`pwd`:$MONO_PATH"
+	# set mono path to support using the Cobra.Core.dll in this directory
+	export MONO_PATH="`pwd`:$MONO_PATH"
+}
 
-if [ -f r-testify.text ]; then
-	mv r-testify.text r-testify-last.text
-fi
+testify() {
+	mono --debug cobra.exe -testify "$@"
+	exitCode=$?
+	if [ $exitCode -ne 0 ]; then
+		((failures++))
+	else
+		((successes++))
+	fi
+	cat $testifyOutputFile >> $tmpOutputFile
+}
 
-time mono --debug cobra.exe -testify "$@"
-exitCode=$?
-if [ $exitCode -ne 0 ]; then
-	echo '"cobra -testify" exited with error code' $exitCode
-	# edit r-testify.text
-	exit 1
-fi
+tearDown() {
+	mv $tmpOutputFile $testifyOutputFile
+}
 
-# edit r-testify.text
+main() {
+	setUp
+	for dir in $dirs ; do
+		heading="\n\n== TESTIFY: $dir\n"
+		echo -e $heading
+		echo -e $heading >> $tmpOutputFile
+		testify "$dir"
+	done
+	# 2012-10-31
+	# these counters are not working correctly right now
+	# on ubuntu 12.04, got 10 failed directories and 11 successes
+	# but there were only 7 tests that failed so the max directories failed would be 7
+	# suspect that "cobra -testify" is exiting with 1 when it should not
+#	if [ $failures -gt 0 ] ; then
+#		msg="Directories that failed: $failures\n"
+#		msg+="Directories that succeeded: $successes"
+#		echo -e $msg
+#		echo -e $msg >> $tmpOutputFile
+#	fi
+	echo "Finished: `date`" >> $tmpOutputFile
+	tearDown
+	if [ $failures -gt 0 ] ; then
+		exit 1
+	fi
+}
+
+time main
+
