Make the cobra script follow symlinks so that cobra.exe can locate resources relative to it.

diff --git a/Source/cobra b/Source/cobra
--- a/Source/cobra
+++ b/Source/cobra
@@ -1,1 +1,14 @@
-mono "`dirname $0`/cobra.exe" $*
+#!/bin/bash
+DIR=`dirname $0`
+if [ -f "$DIR/CobraLang.cobra" ]; then
+	echo "" > /dev/null
+else
+	REALPATH=`readlink -f $0`
+	if [ -f $REALPATH ]; then
+		DIR=`dirname $REALPATH`
+	else
+		echo "error: cannot find CobraLang.cobra"
+		exit 1
+	fi
+fi
+mono "$DIR/cobra.exe" $*
