Check exit code of "cobra -testify".

diff --git a/Source/testify b/Source/testify
--- a/Source/testify
+++ b/Source/testify
@@ -15,5 +15,9 @@ if [ -f r-testify ]; then
 	mv r-testify r-testify-last
 fi
 cobra -testify $*
+if [ $? -ne 0 ]; then
+	echo '"cobra -testify" exited with an error'
+	exit 1
+fi
 clean
 edit r-testify
